# store the results [Now just save the entire "experiments" object]
# write.csv(fig.tables$fig.2c.df, "../SECURE_data/20180608/20180608_pct_var_Dayprior_noDemog_ThreeLambdas.csv",row.names=FALSE)
# write.csv(fig.tables$fig.2c.corr.coefs, "../SECURE_data/20180608/20180608_corr_coefs_Dayprior_noDemog_ThreeLambdas.csv",row.names=FALSE)
# write.table(num.Records, "../SECURE_data/20180608/20180608_Dayprior_noDemog_num_Records.csv",row.names=FALSE,col.names=FALSE, sep=",")
# write.table(num.Records.check, "../SECURE_data/20180608/20180608_Dayprior_noDemog_num_Records_check.csv",row.names=FALSE,col.names=FALSE, sep=",")
# write.table(lasso.features.lambda.manual, "../SECURE_data/20180608/20180608_Dayprior_noDemog_LassoFeaturesLambdaManual.csv",row.names=FALSE,col.names=FALSE, sep=",")
# write.table(lasso.features.lambda.1se, "../SECURE_data/20180608/20180608_Dayprior_noDemog_LassoFeaturesLambda1se.csv",row.names=FALSE,col.names=FALSE, sep=",")
# write.table(lasso.features.lambda.min, "../SECURE_data/20180608/20180608_Dayprior_noDemog_LassoFeaturesLambdaMin.csv",row.names=FALSE,col.names=FALSE, sep=",")
# write.table(rf.features, "../SECURE_data/20180608/20180608_Dayprior_noDemog_RF_Features.csv",row.names=FALSE,col.names=FALSE, sep=",")

# Plot the % var explained
# ggplot(fig.2c.lambda.1se, aes(x=test, y=value, color = variable)) + geom_point(size = 5, aes(shape=variable, color=variable)) +
#   weartals_theme +
#   ylim(0,1) +
#   scale_shape_discrete(breaks=c("vitals", "lasso", "rf"),
#                        labels=c("LM vitals", "LASSO", "RF")) +
#   scale_color_discrete(breaks=c("vitals", "lasso", "rf"),
#                        labels=c("LM vitals", "LASSO", "RF")) +
#   labs(x = "Lab tests",y = expression(paste("Sqrt of % Variance Explained")))

###
# Plot Fig2D with and without demographics
# Note: this currently contains local files generated by running Fig2C code with and without demographics separately and then reading in the files that were generated. 
# Has to be done manually for now, can automate when we decide what the final 2C will look like.

# withDemog <- read.csv("/Users/jessilyn/Desktop/framework_paper/SECURE_data/20180507/20180507_pct_var_Dayprior.csv",
#                       header=TRUE,sep=',',stringsAsFactors=FALSE)
# noDemog <- read.csv("/Users/jessilyn/Desktop/framework_paper/SECURE_data/20180522/20180522_Dayprior_pct_var_noDemog.csv", # 20180531_pct_var_Dayprior_ThreeLambdas.csv"
#                     header=TRUE,sep=',',stringsAsFactors=FALSE)

## categories to color the x-axis
#TODO: UALAB coding causes problems! I removed it from diabetes
clinical.groups = list()
clinical.groups[["Electrolytes"]] =c("CA","K","CL","CO2","NA.","AG")
clinical.groups[["Diabetes"]] =c("A1C","ALB","GLU","CR","ALCRU") #"UALB",
clinical.groups[["Cardiovascular.Disease"]]=c("CHOL","LDLHDL","HDL","CHOLHDL","NHDL","TGL","LDL")
clinical.groups[["Liver Function"]]=c("ALKP","BUN","ALT","TBIL","AST")
clinical.groups[["Inflammation"]]=c("BASO","LYM","LYMAB","MONO","MONOAB","NEUT","NEUTAB","IGM","EOS","EOSAB","BASOAB","WBC","HSCRP")
clinical.groups[["Blood"]] = c("PLT","GLOB","TP","HGB","HCT","RDW","MCH","MCV","RBC","MCHC")

## RF only
withDemog <- read.csv("/Users/jessilyn/Desktop/framework_paper/SECURE_data/20180621/20180621_pct_var_DayPrior_ThreeLambdas.csv",
                      header=TRUE,sep=',',stringsAsFactors=FALSE)[,c("test","rf" )]
noDemog <- read.csv("/Users/jessilyn/Desktop/framework_paper/SECURE_data/20180621/20180621_pct_var_DayPrior_noDemog_ThreeLambdas.csv",
                    header=TRUE,sep=',',stringsAsFactors=FALSE)[,c("test","rf" )]
noDemog[is.na(noDemog)] <- 0; withDemog[is.na(withDemog)] <- 0
withDemog$demog <-"withDemog"
noDemog$demog <- "noDemog"
df <- melt(rbind(withDemog, noDemog), id.vars=c("test", "demog", "shapes"))
withDemog$shapes <- rep("25", length(withDemog$demog))
noDemog$shapes <- rep("24", length(withDemog$demog))
df <- melt(rbind(withDemog, noDemog), id.vars=c("test", "demog", "shapes"))
df$value <- as.numeric(df$value)
df <- df[df$value>0,] # only show those models that actually do well.

#colors for the x-axis labels by clinical.groups
df$col <- rep("NA", length(df$test))
for (i in 1:length(clinical.groups)){
  df$col[df$test %in% clinical.groups[[i]]] <- as.character(myColors[i])
}
df$col[df$col == "NA"] <- "black"
df$test = factor(df$test, levels = as.factor(df$test[order(-df$value)]))

ggplot(df) + 
  geom_point(aes(x=test, y=value, color=variable, shape=as.character(shapes)), size = 4) +
  weartals_theme +
  scale_color_discrete(breaks=c("vitals", "lasso.min", "rf"),
                       labels=c("LM vitals (cVS)", "LASSO (wVS)", "RF (wVS)"),
                       name="Model") +
  scale_shape_discrete(breaks=c("24", "25"),
                       labels=c("Without Demographics", "With Demographics"),
                       name=NULL) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, colour = df$col))




## LM, Lasso, RF
withDemog <- read.csv("/Users/jessilyn/Desktop/framework_paper/SECURE_data/20180622/20180622_pct_var_DayPrior_ThreeLambdas.csv",
                      header=TRUE,sep=',',stringsAsFactors=FALSE)[,c("test","vitals","lasso.min","rf" )]
noDemog <- read.csv("/Users/jessilyn/Desktop/framework_paper/SECURE_data/20180622/20180622_pct_var_DayPrior_noDemog_ThreeLambdas.csv",
                    header=TRUE,sep=',',stringsAsFactors=FALSE)[,c("test","vitals","lasso.min","rf" )]
noDemog[is.na(noDemog)] <- 0; withDemog[is.na(withDemog)] <- 0
withDemog$demog <-"withDemog"
noDemog$demog <- "noDemog"
withDemog$shapes <- rep("25", length(withDemog$demog))
noDemog$shapes <- rep("24", length(withDemog$demog))
df <- melt(rbind(withDemog, noDemog), id.vars=c("test", "demog", "shapes"))
df$test <- factor(df$test, levels = test_levels)
df$value <- as.numeric(df$value)
df$test = factor(df$test, levels = as.factor(df$test[order(-df$value)]))

# figure with upside down & rightside up triangles
ggplot(df) + 
  geom_point(aes(x=test, y=value, color=variable, shape=as.integer(as.character(shapes))), size = 3) +
  weartals_theme +
  scale_color_discrete(breaks=c("vitals", "lasso.min", "rf"),
                       labels=c("LM vitals (cVS)", "LASSO (wVS)", "RF (wVS)"),
                       name="Model") +
  scale_shape_identity()
#  breaks=as.integer(c("24", "25")),
#  labels=c("Without Demographics", "With Demographics"),
#  guide="legend"
# )

# figure with filled triangles and circles
ggplot(df) + 
  geom_point(aes(x=test, y=value, color=variable, shape=as.character(shapes)), size = 4) +
  weartals_theme +
  scale_color_discrete(breaks=c("vitals", "lasso.min", "rf"),
                       labels=c("LM vitals (cVS)", "LASSO (wVS)", "RF (wVS)"),
                       name="Model") +
  scale_shape_discrete(breaks=c("24", "25"),
                       labels=c("Without Demographics", "With Demographics"),
                       name=NULL) 

###
# Calculate difference between top models with and without demographics
model.diff <-max()
demog.diff <- withDemog[,2:4] - noDemog[,2:4]
demog.diff[order(demog.diff$vitals, decreasing=TRUE),]

###
# Plot the top Lasso and RF top features

lasso.features.lambda.manual <- read.csv("../SECURE_data/20180530/20180530_Dayprior_LassoFeaturesLambdaManual.csv",
                                         header=FALSE,sep=',',stringsAsFactors=FALSE)
colnames(lasso.features.lambda.manual) <- c("test", "cv.run", "left.out.person", "lasso.feature",
                                            "lasso.coef.value")
lasso.feature.summaries <- as.data.frame(summarise(group_by(lasso.features.lambda.manual, test, lasso.feature),
                                                   mean=mean(lasso.coef.value), sd=sd(lasso.coef.value)))

# pick top 10 features from each test
top.features <- as.data.frame(lasso.feature.summaries %>% 
                                group_by_(~ test) %>% 
                                top_n(n = 10, wt = abs(mean)))

# figure below is probably better served with a table given the dramatically different scales for the different tests
ggplot(top.features, aes(x=lasso.feature, y=mean, color = test)) + 
  geom_point(size = 3, aes(color=test)) +
  weartals_theme +
  scale_color_discrete(breaks=unique(top.features$test),
                       labels=unique(top.features$test)) +
  labs(x = "Model Features",y = expression(paste("Coefficient")))+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=0.5)

