
# Framework Paper Figures
# built from 20170905_thirtyk.R

#### OUTPUT: Figures for paper

#### LIBRARY DEPENDENCIES:
# install.packages(c("ggplot2","data.table","psych","nlme","MuMIn","Rmisc","gridExtra",
#                    "grid","dplyr","MASS","ggthemes","reshape2","randomForest","glmnet",
#                    "lme4","fasttime","lubridate","tidyr","zoo","parallel","compare","RColorBrewer"))

library(ggplot2)
library(data.table)
library(psych)
library(nlme)
library(MuMIn)
library(Rmisc)
library(gridExtra)
library(grid)
library(dplyr) #plyr
library(MASS)
library("ggthemes")
library(reshape2)
library(randomForest)
library("glmnet")
library(lme4)
require(fasttime) #fastPOSIXct
require(lubridate)
library(tidyr)
require(zoo) #rollapply
library("parallel")
library(compare)
library(RColorBrewer)
library("PMA")

source("ggplot-theme.R") # just to make things look nice

myColors <- c("peachpuff2", "lightskyblue3", "firebrick", "mediumpurple4", "sandybrown", "palegreen4", "salmon")

if(!dir.exists("plots")) dir.create("plots")

# FUNCTIONS
# Get ggplot colors
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}

remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}

findOutlier <- function(data, cutoff = 2) {
  ## Calculate the sd
  sds <- apply(data, 2, sd, na.rm = TRUE)
  ## Identify the cells with value greater than cutoff * sd (column wise)
  result <- mapply(function(d, s) {
    which(d > cutoff * s)
  }, data, sds)
  result
}

filter.nas = function(data, cols){
  cols = cols[cols %in% names(data)]
  if (length(cols) == 0)
    return(data)
  for (col in cols){
    data = data[!is.na(data[,col]),]
  }
  data
}

fastDate <- function(x, tz=NULL)
  #as.Date(fastPOSIXct(x, tz=tz))
  as.Date(x, tz=tz)

# Path to the directory with data
dir = "../SECURE_data/"

###################
#### READ DATA ####
###################

#iPOP wearables/clinical combined data
# wear <- read.csv(paste0(dir, "Basis2016_Cleaned_NotNorm0824_WeekPrior.csv"),
#                  header=TRUE,sep=',',stringsAsFactors=FALSE) # for Lukasz script
# do not use:  wear <- read.csv("/Users/jessilyn/Documents/Career_Development/Mentoring/RyanRunge/20170803_FINAL_LASSOS/Basis2016_Norm0824_WeekPrior.csv",
#                  header=TRUE,sep=',',stringsAsFactors=FALSE) # for other figures, may need to resurrect this one
timespans <-c("AllData",
              "MonthPrior",
              "2WeekPrior",
              "WeekPrior",
              "5DayPrior",
              "3DayPrior",
              "DayPrior" )

wear <- read.csv(paste0(dir, 
                        "Basis2016_Clean_Norm_", timespans[7], "_20180504.csv"),
                 header=TRUE,sep=',',stringsAsFactors=FALSE)
wearables.people <- unique(wear$iPOP_ID)

# iPOP vitals (called vitals in Lukasz script)
#setwd("/Users/jessilyn/Desktop/framework_paper/weartals")
iPOPvitals <- read.csv(paste0(dir, "vitals.csv"),
                       header=TRUE,sep=',',stringsAsFactors=FALSE)
# restrict to wearables only people
iPOPvitals <- iPOPvitals[iPOPvitals$HIMCID %in% wearables.people,]

#iPOP Labs (called labs in Lukasz script)
iPOPlabs <- read.csv(
  paste0(dir, "lab_results_20170717.csv"),
  header=TRUE,sep=',',stringsAsFactors=FALSE)
# restrict to wearables only people
iPOPlabs <- iPOPlabs[iPOPlabs$HIMC_ID %in% wearables.people,]


# 30k vitals
vitals <- fread(paste0(dir, "all_vitals.csv"),
                header=TRUE,sep=',',stringsAsFactors=FALSE)
vitals <- data.frame(vitals)
length(na.omit(vitals$PULSE)) # 552,145
length(na.omit(vitals$TEMPERATURE)) # 333,821

# 30k labs
labs <- fread(paste0(dir, "all_labs.csv"),
              header=TRUE,sep=',',stringsAsFactors=FALSE)
# 30K labs/vitals combined file <- generated by 20170908_thirtyk.R or 20180412_thirtyk.R (where new vitals like BP and respiration are added in)
# corDf <- read.csv(paste0(dir, "20170905_Cleaned_joined_30k_labs_vitals.csv"),
#                    header=TRUE,sep=',',stringsAsFactors=FALSE)
corDf <- read.csv(paste0(dir, "20180412_Cleaned_joined_30k_labs_ALLvitals.csv"),
                  header=TRUE,sep=',',stringsAsFactors=FALSE)
#30k Codes
icd <- fread(paste0(dir, "all_icds.csv"),
             header=TRUE,sep=',',stringsAsFactors=FALSE)
cpt <- fread(paste0(dir, "all_cpts.csv"),
             header=TRUE,sep=',',stringsAsFactors=FALSE)

#iPOP demographics
iPOPdemographics <- read.csv(paste0(dir, "SECURE_ClinWearDemo_SamplePop.csv"),
                             header=TRUE,sep=',',stringsAsFactors=FALSE)

### TODO: get data from Jessie
# iPOPicd <-fread(paste0(dir, "diagnoses_110718.csv"),
#                 header=TRUE,sep=',',stringsAsFactors=FALSE)
# iPOPcpt <-fread(paste0(dir, "procedures_110718.csv"),
#                 header=TRUE,sep=',',stringsAsFactors=FALSE)

#thirtyK demographics
thirtyKdemog <- read.csv(paste0(dir, "SECURE_20180412_thirtyKDemog.csv"),
                         header=TRUE,sep=',',stringsAsFactors=FALSE)

# names of top clinical tests that will be used for the downstream analyses
top.names<-top.names<-c("LYM", "NEUT", "LYMAB", "NEUTAB", "IGM", "HSCRP", "ALKP", "ALT", "HDL", "MCV", "TBIL", "CHOLHDL", "GLOB", "AG", "CO2", "CA", "LDLHDL", "BUN", "NHDL", "NA.", "UALB", "MONOAB", "CHOL", "MONO", "RDW", "HCT", "TP", "TGL", "EOS", "LDL", "GLU", "AST", "PLT", "K", "EOSAB", "BASOAB", "MCH", "ALB", "HGB", "A1C", "CL", "RBC", "BASO", "MCHC") # names of lab tests from the 30k simple bivariate models




###################
### CLEAN DATA ####
###################

### clean iPOP Vitals ###
names(iPOPvitals)[which(names(iPOPvitals)=="HIMCID")] <- "iPOP_ID"
names(iPOPvitals)[which(names(iPOPvitals)=="RECORDED_TIME")] <- "Clin_Result_Date"
names(iPOPvitals)[which(names(iPOPvitals)=="X.Pulse.")] <- "Pulse"
names(iPOPvitals)[which(names(iPOPvitals)=="X.Temp.")] <- "Temp"
names(iPOPvitals)[which(names(iPOPvitals)=="X.BP.")] <- "BP"
names(iPOPvitals)[which(names(iPOPvitals)=="X.Bmi.")] <- "BMI"

for (i in 1:length(iPOPvitals$BP)){
  iPOPvitals$systolic[i] <- strsplit(as.character(iPOPvitals$BP),'/')[[i]][1]
  iPOPvitals$diastolic[i] <- strsplit(as.character(iPOPvitals$BP),'/')[[i]][2]
}

#Reformat dates
iPOPvitals$Clin_Result_Date <- format(
  as.Date(iPOPvitals$Clin_Result_Date, "%d-%b-%Y"), "%Y-%m-%d")


#Make correlation variables numeric
iPOPvitals[,c("Pulse","Temp","BP","BMI","systolic", "diastolic")] <- apply(
  iPOPvitals[,c("Pulse","Temp","BP","BMI","systolic", "diastolic")], 2,
  function(x) as.numeric(as.character(x)))

#### CLEAN iPOP LABS DATA ####

#Rename columns
names(iPOPlabs)[which(names(iPOPlabs)=="HIMC_ID")] <- "iPOP_ID"
names(iPOPlabs)[which(names(iPOPlabs)=="RESULT_TIME")] <- "Clin_Result_Date"

#Reformat dates
iPOPlabs$Clin_Result_Date <- format(
  as.Date(iPOPlabs$Clin_Result_Date, "%d-%b-%Y"), "%Y-%m-%d")

allClin <- c("ALKP", "LYM", "HSCRP", "ALT", "NEUT", "TBIL", "IGM", "TGL", "MCV", "MCH", "CO2", "LYMAB", "NEUTAB", "UALB", "CHOL", "MONOAB", "ALB", "NA.", "HDL", "PLT", "AG", "HGB", "EOS", "CL", "BUN", "GLOB", "CA", "CHOLHDL", "HCT", "BASOAB", "A1C", "GLU", "LDLHDL", "TP", "EOSAB", "K", "NHDL", "RBC", "MONO", "AST", "MCHC", "RDW", "BASO", "LDL")

for(i in 1:length(allClin)){ #this removes non-numeric characters
  cache <- iPOPlabs[,c(allClin[i])]
  cache <- gsub("[^0-9.]","",cache) #this keeps decimals
  iPOPlabs[,c(allClin[i])] <- cache
}

#Make correlation variables numeric
iPOPlabs[,c(allClin)] <- apply(
  iPOPlabs[,c(allClin)], 2,
  function(x) as.numeric(as.character(x)))

#subset by allClin
iPOPlabs <- iPOPlabs[names(iPOPlabs) %in% c("iPOP_ID","Clin_Result_Date",allClin)]

#Merge data
iPOPcorDf <- merge(iPOPlabs,
                   iPOPvitals[,c("iPOP_ID","Clin_Result_Date",
                                 "Pulse","Temp","BMI","systolic","diastolic")],
                   by=c("iPOP_ID","Clin_Result_Date"))

iPOPcorDf2 <- iPOPcorDf
### clean iPOPcorDf ###
iPOPcorDf[, -c(1,2)] <- apply(iPOPcorDf[, -c(1,2)], 2, remove_outliers)
outliers <- findOutlier(iPOPcorDf)
comparison <- compare(iPOPcorDf,iPOPcorDf2,allowAll=TRUE)
difference <-
  data.frame(lapply(1:ncol(iPOPcorDf),function(i)setdiff(iPOPcorDf[,i],comparison$tM[,i])))
colnames(difference) <- colnames(iPOPcorDf)
difference #no data points are removed.

### clean corDf ### 
summary(corDf)
corDf2 <- corDf
corDf[, -c(1,2)] <- apply(corDf[, -c(1,2)], 2, remove_outliers) 

comparison <- compare(corDf,corDf2,allowAll=TRUE)
difference <-
  data.frame(lapply(1:ncol(corDf),function(i)setdiff(corDf[,i],comparison$tM[,i])))
colnames(difference) <- colnames(corDf)
difference
outliers <- findOutlier(corDf) # http://rpubs.com/lcollado/7904

## clean 30k icd and cpt dates
icd$ICD_DATE <- format(
  as.Date(icd$ICD_DATE, "%d-%b-%Y"), "%Y-%m-%d")
icd$ICD_DATE <- as.Date(icd$ICD_DATE, "%Y-%m-%d")
cpt$CPT_DATE <- format(
  as.Date(cpt$CPT_DATE, "%d-%b-%Y"), "%Y-%m-%d")
cpt$CPT_DATE <- as.Date(cpt$CPT_DATE, "%Y-%m-%d")

### clean wear ### messes up code for Fig 2C so edited it out, but might be necessary for the CCA in Fig 2E
# wear2<-wear
# wear[,-c(1:6)] <- apply(wear[,-c(1:6)], 2, function(x) as.numeric(as.character(x)))
# wear[,-c(1:6)] <- apply(wear[,-c(1:6)], 2, remove_outliers) 

## merge iPOP and demographics
iPOPcorDf.demo <- merge(iPOPcorDf, iPOPdemographics[1:4], by="iPOP_ID")

source("scripts/helper-functions.R")
